### ISSUE TITLE
Add ability to update to most recent code

### ISSUE THREAD

**Issue by I-Am-Umbrella** [alexrudd2/saxi#138]
add the ability to update to the latest code

**Comment by alexrudd2** [comment]
This already exists.

Method 1: For installs using the package published on [NPM](https://www.npmjs.com/package/saxi), run `npm update -g saxi`.  Note that `nornagon` controls the NPM package, and he hasn't published a new version in quite some time.

Method 2: For installs directly from git, go to the install folder and run `git pull` and then `npm install`.  (This is what I did on the OrangePIs)
