### ISSUE TITLE
Add new `cli pen <percent>` command to help debug

### ISSUE THREAD

**Issue by alexrudd2** [alexrudd2/saxi#90]
> Add new `cli pen <percent>` command to help debug a bit.

_Originally posted by @jedahan in https://github.com/alexrudd2/saxi/issues/88#issuecomment-1741875235_

Note that there is some code which appears strange regarding the pen up/down.  See https://github.com/nornagon/saxi/issues/90.  Apparently some hardware has the pen direction reversed, so it's not always clear whether `0` = down and `100` = up, or vice versa.

**Comment by jedahan** [comment]
see #92

**Comment by alexrudd2** [comment]
I should be able to test on (brushed) hardware in the next few days.

**Comment by alexrudd2** [comment]
It works :)
